### ISSUE TITLE
session can't config

### ISSUE THREAD

**Issue by klaus20141002** [ityouknow/spring-boot-examples#1]
session 模块，好像一直走缓存，即
便更改失效时间也没有用，还请帮忙梳理一下
![image](https://cloud.githubusercontent.com/assets/8716969/23400550/5ff567a0-fddf-11e6-9246-ceef0d750118.png)

**Comment by xoyang** [comment]
Error creating bean with name 'enableRedisKeyspaceNotificationsInitializer' defined in class path resource 

我运行的是 spring-boot-web
我如果不想运行redis那关闭了POM，排除了CONFIG等文件，properties文件，还是运行不起来。求助一下，谢谢。

**Comment by ityouknow** [comment]
能把报错信息贴出来吗
