### ISSUE TITLE
springboot2.1.5版本配置session共享

### ISSUE THREAD

**Issue by maxlange** [ityouknow/spring-boot-examples#107]
最新springboot2.1.5版本配置session共享时，session自动配置的注解不能起作用，并且会报找不到security的rememberservice的错误，是依赖包不兼容吗

**Comment by qcmoke** [comment]
> 最新springboot2.1.5版本配置session共享时，session自动配置的注解不能起作用，并且会报找不到security的rememberservice的错误，是依赖包不兼容吗

我也遇到了同样的问题，你的解决了吗？

**Comment by wuqi5689** [comment]
升级到2.1.6
