### ISSUE TITLE
java发送邮件被认为垃圾邮件

### ISSUE THREAD

**Issue by xiaxuchen** [ityouknow/spring-boot-examples#117]
有什么方法能让qq、163等服务器不将我的邮件退信吗？没发几封就退信，垃圾邮件，java这样发邮件或许还不如请个员工来手动发。博客园、csdn等等大一点的网站发送的邮件就很稳定，是因为他们是企业邮箱吗？有什么方法可以稳定发送邮件啊

**Comment by ityouknow** [comment]
用第三方的服务，有些是收费的。
