### ISSUE TITLE
maven dependency can not download ？？？

### ISSUE THREAD

**Issue by yanghui8837** [ityouknow/spring-boot-examples#123]
这个项目里用的fastdfs-client-java 一直下不下来 用外网也不行 
      <dependency>
            <groupId>org.csource</groupId>
            <artifactId>fastdfs-client-java</artifactId>
            <version>1.27-SNAPSHOT</version>
        </dependency>      

fastdfs-client不应该用下面这个么 ？

     <dependency>
            <groupId>com.github.tobato</groupId>
            <artifactId>fastdfs-client</artifactId>
            <version>1.26.1-RELEASE</version>
        </dependency>

**Comment by yanghui8837** [comment]
并且mvnrepository也只有1.27-RELEASE  https://mvnrepository.com/artifact/org.csource/fastdfs-client-java 并没有1.27-SNAPSHOT版本

**Comment by coy0725** [comment]
我也有这个问题，Cannot resolve org.csource:fastdfs-client-java:1.27-SNAPSHOT

**Comment by ityouknow** [comment]
这个是 fastdfs 本地的jar 包，可以网上去搜索自行下载。
