### ISSUE TITLE
真的垃圾，跑都跑不起来，入门就是bug，真的服了，都不知道完善了再上传

### ISSUE THREAD

**Issue by puchao-org** [ityouknow/spring-boot-examples#127]

**Comment by ityouknow** [comment]
@puchao-org 先找自己的问题，你这样的态度应该学不好技术

**Comment by puchao-org** [comment]
同样的话，送给你自己




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"纯洁的微笑"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月18日(星期六) 中午1:02
收件人:&nbsp;"ityouknow/spring-boot-examples"<spring-boot-examples@noreply.github.com&gt;;
抄送:&nbsp;"我思故我在"<1819146844@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ityouknow/spring-boot-examples] 真的垃圾，跑都跑不起来，入门就是bug，真的服了，都不知道完善了再上传 (#127)





 
@puchao-org 先找自己的问题，你这样的态度应该学不好技术
