### ISSUE TITLE
跑不起来，入门就是bug，这些烂项目才是新手学习最大的障碍

### ISSUE THREAD

**Issue by puchao-org** [ityouknow/spring-boot-examples#128]
v-mysql is up-to-date
Starting v-nginx ... error

ERROR: for v-nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint v-nginx

**Comment by q350241636** [comment]
赞同
我是.net 开发，想从头学一下springboot 
java代码是真简单，这破玩意配置半天跑不起来 
撤了

**Comment by signner** [comment]
> 赞同
> 我是.net 开发，想从头学一下springboot
> java代码是真简单，这破玩意配置半天跑不起来
> 撤了

这东西不很简单的吗。。哪来那么多bug

**Comment by q350241636** [comment]
> > 赞同
> > 我是.net 开发，想从头学一下springboot
> > java代码是真简单，这破玩意配置半天跑不起来
> > 撤了
> 
> 这东西不很简单的吗。。哪来那么多bug

代码是真的简单 就是启动配置啥的 真恶心  一个依赖包还需要手动下载引入 
![image](https://user-images.githubusercontent.com/38104555/102199168-3f53bd80-3efe-11eb-99fb-7a070a37aad6.png)
