### ISSUE TITLE
请问启动Hello word 项目为什么会用到dfs

### ISSUE THREAD

**Issue by q350241636** [ityouknow/spring-boot-examples#142]
请问启动Hello word 项目为什么会用到dfs

WARNING] The POM for org.csource:fastdfs-client-java:jar:1.27-SNAPSHOT is missing, no dependency information available	

<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	     <dependency>
	        <groupId>org.springframework.boot</groupId>
	        <artifactId>spring-boot-devtools</artifactId>
	        <optional>true</optional>
		</dependency>
	</dependencies>

**Comment by Dark-knight-404** [comment]
用spring boot简单的写hello word 不需要导入这个fastdfs包


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ityouknow/spring-boot-examples"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月15日(星期二) 晚上6:02
收件人:&nbsp;"ityouknow/spring-boot-examples"<spring-boot-examples@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ityouknow/spring-boot-examples] 请问启动Hello word 项目为什么会用到dfs (#142)





 
请问启动Hello word 项目为什么会用到dfs
 
WARNING] The POM for org.csource:fastdfs-client-java:jar:1.27-SNAPSHOT is missing, no dependency information available
 		 			org.springframework.boot 			spring-boot-starter-web 		 		 			org.springframework.boot 			spring-boot-starter-test 			test 		 	      	        org.springframework.boot 	        spring-boot-devtools 	        true

**Comment by ityouknow** [comment]
勿加的，去掉了。

**Comment by ityouknow** [comment]
@q350241636 哪个项目有  hello world 里面没找到有？

**Comment by q350241636** [comment]
> @q350241636 哪个项目有 hello world 里面没找到有？

https://github.com/ityouknow/spring-boot-examples/tree/master/spring-boot-helloWorld
这不是hello word吗

我在这个项目里 运行Application的main方法 为什么会给所有项目都编译一遍呢？
