### ISSUE TITLE
spring-boot-file-upload demo上传图片到 "E://temp//"   怎么通过地址访问图片呀？

### ISSUE THREAD

**Issue by gionlime** [ityouknow/spring-boot-examples#148]
spring-boot-file-upload demo上传图片到 "E://temp//"   怎么通过地址访问图片呀？
![image](https://user-images.githubusercontent.com/91245043/138060971-ed25bb0c-7b9f-4672-b5ab-d8d69fbab038.png)

**Comment by gionlime** [comment]
`package com.config;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.ResourceHandlerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
 

@Configuration
public class UploadFilePathConfig implements WebMvcConfigurer {
    // @Value("${file.staticAccessPath}")
    // private String staticAccessPath;
    // @Value("${file.uploadFolder}")
    // private String uploadFolder;
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/**").addResourceLocations("file:E:/temp/");
    }
}`

**Comment by gionlime** [comment]
http://localhost:8080/dash.png

**Comment by DionQiu** [comment]
不能这样访问  走controller的方式请求访问 将图片流写到reponse
