### ISSUE TITLE
Please add an English version of the documents

### ISSUE THREAD

**Issue by linhtch90** [ityouknow/spring-boot-examples#151]
Hello,

This is a very great repository. However, will you please add an English version for all the documents so non-Chinese speaker can understand the projects here better?

Thanks!

**Comment by Joechens** [comment]
您好，邮件我已收到，会尽快回复。

**Comment by suncong529** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zhaojieip** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by ityouknow** [comment]
I suggest you learn Chinese

**Comment by Joechens** [comment]
您好，邮件我已收到，会尽快回复。

**Comment by suncong529** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
