### ISSUE TITLE
spring-boot-web项目的pom.xml配置有误

### ISSUE THREAD

**Issue by Zychaowill** [ityouknow/spring-boot-examples#19]
<dependency>  
	<groupId>org.springframework.boot</groupId>  
        <artifactId>spring-boot-starter-redis</artifactId>  
</dependency> 
需要改为:
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-redis</artifactId>
</dependency>

**Comment by ityouknow** [comment]
不同的版本使用的不一样，最新版本使用的是spring-boot-starter-data-redis
