### ISSUE TITLE
参数类型由Long改成long是不是更好一点

### ISSUE THREAD

**Issue by lzhp** [ityouknow/spring-boot-examples#21]
我看很多参数都写的是Long，是不是改成long通用性更好一点？

**Comment by LincyC** [comment]
参数方法好像还是用类对象好点，基础数据类型反而不好控制。（具体为啥我也不太懂= =）

**Comment by lzhp** [comment]
学习了一下，类类型可以NULL，值类型天然有默认值，与数据库很可能不对应，所以类对象好点
