### ISSUE TITLE
在eclipse中导入spring-boot-jpa-thymeleaf-curd后报错

### ISSUE THREAD

**Issue by greatzerg** [ityouknow/spring-boot-examples#31]
@ityouknow 
以maven项目为模式导入spring-boot-jpa-thymeleaf-curd后，java类在报错：
![image](https://user-images.githubusercontent.com/8281596/34857514-2293e642-f786-11e7-9bb1-5b4b92edbc85.png)
点击
![image](https://user-images.githubusercontent.com/8281596/34857520-2a714b34-f786-11e7-8086-c131f5bbe0fe.png)后，看到这些maven中配置的jar包都已经引入到了项目中
![image](https://user-images.githubusercontent.com/8281596/34857485-f703b142-f785-11e7-8ad7-75624158c062.png)
请问这种报错应该如何解决呢？

**Comment by ityouknow** [comment]
建议使用ieda，
