### ISSUE TITLE
Spring Boot推荐资源

### ISSUE THREAD

**Issue by ityouknow** [ityouknow/spring-boot-examples#35]
给网站 http://springboot.fun/ 推荐资源请留言

**Comment by grath10** [comment]
@ityouknow 群主进群235789304暗号是什么？

**Comment by ityouknow** [comment]
@grath10 在公号里面回复：springboot

**Comment by HoldDie** [comment]
强哥，很稳

**Comment by grath10** [comment]
@ityouknow 好的，多谢

**Comment by ityouknow** [comment]
@IsoSun  http://springcloud.fun/  这个就是。
