### ISSUE TITLE
如何使用JPA保存Hibernate的多对多关系表

### ISSUE THREAD

**Issue by HelloGril** [ityouknow/spring-boot-examples#43]
用户、权限、角色三个表为多对多的关系，如何用jpa来初始化数据呢？能麻烦您指导一下吗？非常感谢

**Comment by ityouknow** [comment]
我博客有一篇权限shiro的文章，可以看看

**Comment by HelloGril** [comment]
嗯 看了您的文章，文章里初始化数据是使用sql，如果是用Spring data jpa 的 save 方法来初始化数据该如果写呢？
