### ISSUE TITLE
FASTDFS工具类封装有问题

### ISSUE THREAD

**Issue by AlexLiy1** [ityouknow/spring-boot-examples#45]
trackerServer = trackerClient.getConnection();
storageServer = trackerClient.getStoreStorage(trackerServer);
使用时获取，不应该直接静态化掉，当服务某个节点故障时，正好是你静态化的节点就会导致服务不可用。破化了原有可用性。

**Comment by ityouknow** [comment]
@AlexLiy1 感谢反馈

**Comment by ityouknow** [comment]
@AlexLiy1  已经修复，感谢反馈。
