### ISSUE TITLE
CollectView 中方法顺序与SQL字段顺序

### ISSUE THREAD

**Issue by xuxfei** [ityouknow/spring-boot-examples#49]
HomeController中：

![image](https://user-images.githubusercontent.com/5073459/40353957-4d9fde5c-5de5-11e8-855d-c13ff5898fe5.png)

![image](https://user-images.githubusercontent.com/5073459/40354035-85f0eb48-5de5-11e8-8ffc-8e79071b4408.png)

userid的数据类型为long，但是返回的views中为字符串，最终报错：
![image](https://user-images.githubusercontent.com/5073459/40354168-d2ef4c14-5de5-11e8-937f-ebf57e886338.png)

测试发现，将接口CollectView 内方法的顺序，与SQL字段的顺序调整一致，可解决，但是不明白为什么，麻烦大神是否可以解答一下？

**Comment by xuxfei** [comment]
提错地方了：
是 favorites-web 项目的 issue

**Comment by ityouknow** [comment]
@xuxfei  看看最新版本吧。
