### ISSUE TITLE
参考文章链接失效

### ISSUE THREAD

**Issue by benling** [ityouknow/spring-boot-examples#50]
readme里面的参考文章链接全部都失效了，是否移到其它站点了？

**Comment by ityouknow** [comment]
@benling  我的博客：www.ityouknow.com 正在备案，预计一周后完成，完成后就可以访问。如果着急可以先放问临时链接：www.mooooc.com

**Comment by benling** [comment]
好的，非常感谢，准备启用spring boot项目，学习下。
