### ISSUE TITLE
RabbitMQ测试问题

### ISSUE THREAD

**Issue by liuzehonga** [ityouknow/spring-boot-examples#54]
在RabbitMQ例子中，测试的时候出现不能注入的问题
Error creating bean with name 'com.example.demo.hello.HelloTest': Unsatisfied dependency expressed through field 'helloSender'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.example.demo.hello.HelloSender' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

**Comment by baked-pan** [comment]
1. 检查`@Bean`注解所在类有没有加类注解`@Configuration`
2. 在`helloSender`定义的时候,加入名称定义`@Bean(name = "helloSender")`
