### ISSUE TITLE
spring-boot-shiro 提示缺失 bean authenticator

### ISSUE THREAD

**Issue by Aaronffp** [ityouknow/spring-boot-examples#56]
现象：
依据提供的示例中的源码参考写了一个（仅表结构有所差异），启动时提示如下错误信息：

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method authorizationAttributeSourceAdvisor in com.shenma.pmp.config.ShiroConfig required a bean named 'authenticator' that could not be found.

Action:

Consider defining a bean named 'authenticator' in your configuration.

存在的主要差异在表结构方面，config、dao、service、controller 一样，请问是什么原因呢？非常感谢！

**Comment by bwensun** [comment]
> 如果没猜错的话，是你在注入securityManager的时候是这么写的
> 
> ` @Bean public SecurityManager securityManager() {……}`
> 
> 改为默认的即可：
> `@Bean public DefaultWebSecurityManager securityManager() {……}`
> 
> >

你说的很对，我震惊了，居然是这个原因

**Comment by MJJKG5** [comment]
被猜到了！！！能说说为什么用DefaultWebSecurityManager

**Comment by MJJKG5** [comment]
被猜到了！！！

**Comment by MJJKG5** [comment]
被猜到了！！
能说说为什么使用DefaultWebSecurityManager类问题解决，而使用SecurityManager出现问题。
我使用的jar包是shiro-spring-boot-web-starter

**Comment by OliverSeth** [comment]
同，想知道为什么

**Comment by pluveto** [comment]
同，想知道为什么
