### ISSUE TITLE
dockercompose-springboot-mysql-nginx的问题

### ISSUE THREAD

**Issue by hello-willy** [ityouknow/spring-boot-examples#59]
大神你好：在看到您的文章《Spring Boot 2.0(五)：Docker Compose + Spring Boot + Nginx + Mysql 实践》后我亲自试验了一下，发现到最后执行docker-compose up时mvn命令总是提示找不到pom文件，通过分析docker-compose.yaml文件，我发现关于app服务的命令描述是：mvn clean spring-boot:run -Dspring-boot.run.profiles=docker，而在执行docker-compose up命令的目录实在dockercompose-springboot-mysql-nginx目录，即app的父目录，因为spring boot工程在app中，所以在执行mvn命令时mvn会在当前目录（dockercompose-springboot-mysql-nginx）寻找pom文件，所以找不到，对于Docker我是新手，我真不知道这里的问题在哪？您能给指点迷津吗？非常感谢！

**Comment by maskchair** [comment]
先把springboot项目写出来，springboot项目能运行成功的时候，再docker化项目
