### ISSUE TITLE
你这个项目是怎么跑起来的啊

### ISSUE THREAD

**Issue by jarvissdiff** [ityouknow/spring-boot-examples#64]
请问你这个路径是怎么来的import org.apache.shiro.web.mgt.DefaultWebSecurityManager;我在shiro包下完全找不到mgt的路径啊，shiro-spring-1.4.0

![image](https://user-images.githubusercontent.com/43332439/45608728-1b874000-ba87-11e8-8756-a4a477382e7a.png)

**Comment by jarvissdiff** [comment]
spring-boot-shiro项目

**Comment by jarvissdiff** [comment]
你是完全复制粘贴，没有验证过就发教程的吗？

**Comment by BruceKellan** [comment]
项目是没问题的，shiro-spring依赖了shiro-web这个包，在shiro-web包下
