### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by developerRoger** [ityouknow/spring-boot-examples#66]
我有个问题， 那就是怎么看springboot的运行日志，我现在将日志输出的位置是/home/log这个文件夹，但是生成不了日志，用tomat部署又可以，用docker就不行，你们都是怎么看日志的啊。要建个软连接到docker里面生成一个文件夹映射到外部吗

**Comment by ityouknow** [comment]
可以通过配置文件来配置输出的地址，可以查看 www.ityouknow.com 中的文章示例。
