### ISSUE TITLE
Missing artifact org.csource:fastdfs-client-java:jar:1.27-SNAPSHOT

### ISSUE THREAD

**Issue by luoxianjiao** [ityouknow/spring-boot-examples#69]
<dependency>
            <groupId>org.csource</groupId>
            <artifactId>fastdfs-client-java</artifactId>
            <version>1.27-SNAPSHOT</version>
        </dependency>
这个jar在那个库呢？

**Comment by geduo4612** [comment]
fastdfs-client-java 1.27-SNAPSHOT 的依赖项，maven是不能直接下载的，我是参考[http://www.mamicode.com/info-detail-2329592.html](url)实现的。

**Comment by ityouknow** [comment]
fastdfs-client-java 地址：
https://github.com/happyfish100/fastdfs-client-java

我一般都是将这个项目下载下来在工程中导入来使用。@luoxianjiao

**Comment by q350241636** [comment]
我就想问一下 我就启动个hello word 
怎么就依赖上fastdfs包了？
