### ISSUE TITLE
spring-boot-mongodb遇到错误，incompatible types ，具体见下图

### ISSUE THREAD

**Issue by Michael728** [ityouknow/spring-boot-examples#70]
试着创建了工程，在这里遇到了一个错误，有人指导一下吗？
![](https://ws2.sinaimg.cn/large/006tNbRwly1fwg3wek57nj30hc0obadw.jpg)

**Comment by ityouknow** [comment]
你使用的是 2.0的版本吗？

**Comment by ityouknow** [comment]
示例 已经升级到 2.X 了，可以下载下来重新测试。
