### ISSUE TITLE
springboot + mongodb

### ISSUE THREAD

**Issue by SummerXia93** [ityouknow/spring-boot-examples#73]
-- I am using the springboot 1.5.10 and mongodb 2.0.4 to do my develop;

-- I already build 2 relevant mongo collections.
   e.g. student and teacher collections, while student id list is an attribute of teacher.

-- I want to make this happen: if a student is expired by time and got deleted from its collection,  it will be erased from the list in the relevant teacher too. Like in mysql it will be easy to do.

-- Now I already add the @DBRef annotation on the list attribute of teacher, but when a student got expired and deleted, the element of the list will become null instead of got erased.

Is anyone know how to make the element deleted instead of becoming null?

**Comment by 88denooyer** [comment]
Here's the code I use

In your controller class:
`@RequestMapping("/delete")
public String delete(@RequestParam String id) {
    Object <objectName> = <repository class>.findOne(id);
    <repository class>.delete(<object name>);

    return "redirect:/<name>";`

In your repository class:
`public interface <repository name> extends CrudRepository<Object, String> {
    @Override
    Object findOne(String id);

    @Override
    void delete(Object deleted);
}`

Hope this works for you!
