### ISSUE TITLE
发送附件邮件问题

### ISSUE THREAD

**Issue by linyongfu2013** [ityouknow/spring-boot-examples#76]
老师，您好，首先非常感谢您的课程。

有个问题请教下，假设我的邮件服务是做成了微服务的架构，我的其它系统需要调用邮件服务接口发送附件，这个附件可能在其它服务器上，甚至在OSS云上，那这个附件参数应该如何传递给邮件服务接口呢？

感谢您的时间。

**Comment by ityouknow** [comment]
给一个可以访问的地址就行。
