### ISSUE TITLE
spring-boot-jpa-thymeleaf-curd 使用mysql8会报错，附解决方法

### ISSUE THREAD

**Issue by OMGZui** [ityouknow/spring-boot-examples#79]
解决办法如下：

- 修改`spring.datasource.url=jdbc:mysql://localhost:3307/mac?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8&serverTimezone=GMT&useSSL=false`
- 修改`spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver`
- 新增`spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect`

希望能帮到遇到问题的老弟

**Comment by ityouknow** [comment]
感谢反馈 @OMGZui
