### ISSUE TITLE
注解问题（实体类）

### ISSUE THREAD

**Issue by zhonghuazhi** [ityouknow/spring-boot-examples#80]
https://github.com/ityouknow/spring-boot-examples/blob/b7423ddbcbbb6758af66f735ab1f92da2fdc6075/spring-boot-web/src/main/java/com/neo/domain/User.java#L16

您好，经过运行程序，发现在数据库中会自动生成相对应的表，不过额外还会在生成出来一个序列。

**Comment by ityouknow** [comment]
嗯 貌似是高版本后有的。
