### ISSUE TITLE
springboot2.1集成redis，启动提示 “Failed to bind properties under 'spring.redis.timeout' to long:”

### ISSUE THREAD

**Issue by donfaquir** [ityouknow/spring-boot-examples#82]
新版本依赖的是spring-boot-starter-data-redis，在获取LettuceClientConfiguration的时候，会报错，提示spring.redis.timeout的类型转换错误，代码是：
LettuceClientConfiguration lettuceClientConfiguration = LettuceClientConfiguration.builder().
                useSsl().and()
                .commandTimeout(redisProperties.getTimeout())
                .shutdownTimeout(Duration.ZERO)
                .build();
redisProperties是注入的，调试看这个实例数据正常转换了。是Duration类型的

哪位知道怎么解决

**Comment by ityouknow** [comment]
请使用示例中的源码来测试。
