### ISSUE TITLE
好像不用写那个mybatis-config.xml 和baseresulttype也可以

### ISSUE THREAD

**Issue by houguiqiang** [ityouknow/spring-boot-examples#9]
1、首先mybatis-config.xml文件不需要也可以
2、usermapper.xml里面的baseresulttype那个一段不需要也可以

**Comment by ityouknow** [comment]
@houguiqiang 具体是里面那个项目呢。

**Comment by houguiqiang** [comment]
spring-boot-mybatis-xml（非注解方式）
